"""add_zoom_fields_to_sessions

Revision ID: 2c1f98e68084
Revises: c7839372fe86
Create Date: 2025-08-15 16:39:35.203139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1f98e68084'
down_revision = 'c7839372fe86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('meeting_password', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('meeting_start_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('meeting_uuid', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('meeting_uuid')
        batch_op.drop_column('meeting_start_url')
        batch_op.drop_column('meeting_password')
        batch_op.drop_column('meeting_id')

    # ### end Alembic commands ###
