"""Add moodle start and end dates to modules table

Revision ID: 361ff2ceef7d
Revises: d2e731c7646d
Create Date: 2025-08-15 19:40:39.950527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361ff2ceef7d'
down_revision = 'd2e731c7646d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moodle_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('moodle_end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_column('moodle_end_date')
        batch_op.drop_column('moodle_start_date')

    # ### end Alembic commands ###
