"""Add availability_id to sessions table

Revision ID: 410af0de3982
Revises: bd4e5a569118
Create Date: 2025-08-16 10:03:45.513141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410af0de3982'
down_revision = 'bd4e5a569118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability_id', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_sessions_availability_id', 'availability', ['availability_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sessions_availability_id', type_='foreignkey')
        batch_op.drop_column('availability_id')

    # ### end Alembic commands ###
