"""Add lesson_id to sessions table

Revision ID: 8c45f108d04b
Revises: 2c1f98e68084
Create Date: 2025-08-15 18:40:38.838809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c45f108d04b'
down_revision = '2c1f98e68084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_id', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_sessions_lesson_id', 'lessons', ['lesson_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sessions_lesson_id', type_='foreignkey')
        batch_op.drop_column('lesson_id')

    # ### end Alembic commands ###
