"""add availability exceptions table

Revision ID: ae45f89c12d3
Revises: 2c1f98e68084
Create Date: 2025-09-16 23:35:30.000000

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'ae45f89c12d3'
down_revision = '2c1f98e68084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_exceptions',
        sa.Column('id', sa.String(length=50), nullable=False),
        sa.Column('parent_availability_id', sa.String(length=50), nullable=False),
        sa.Column('exception_date', sa.Date(), nullable=False),
        sa.Column('exception_type', sa.String(length=20), nullable=False),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, default=datetime.utcnow),
        sa.Column('created_by', sa.String(length=50), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['parent_availability_id'], ['availability.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
        sa.UniqueConstraint('parent_availability_id', 'exception_date', name='unique_exception_per_date')
    )

    # Create indexes for better query performance
    op.create_index('idx_availability_exceptions_parent_id', 'availability_exceptions', ['parent_availability_id'])
    op.create_index('idx_availability_exceptions_date', 'availability_exceptions', ['exception_date'])
    op.create_index('idx_availability_exceptions_type', 'availability_exceptions', ['exception_type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_availability_exceptions_type', table_name='availability_exceptions')
    op.drop_index('idx_availability_exceptions_date', table_name='availability_exceptions')
    op.drop_index('idx_availability_exceptions_parent_id', table_name='availability_exceptions')
    op.drop_table('availability_exceptions')
    # ### end Alembic commands ###