"""Remove moodle_start_date and moodle_end_date columns

Revision ID: bd4e5a569118
Revises: 361ff2ceef7d
Create Date: 2025-08-16 00:30:01.294332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd4e5a569118'
down_revision = '361ff2ceef7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_column('moodle_start_date')
        batch_op.drop_column('moodle_end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moodle_end_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('moodle_start_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
