"""add_course_id_to_availability_table

Revision ID: c7839372fe86
Revises: cb3334738232
Create Date: 2025-08-15 15:03:10.713072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7839372fe86'
down_revision = 'cb3334738232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_availability_course_id', 'courses', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_constraint('fk_availability_course_id', type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
