"""Add BulkImportJob table for tutor qualification imports

Revision ID: ea557514914b
Revises: d771d243b138
Create Date: 2025-09-15 07:23:37.986248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea557514914b'
down_revision = 'd771d243b138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_import_jobs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('job_status', sa.String(length=20), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('import_type', sa.String(length=20), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('successful_records', sa.Integer(), nullable=True),
    sa.Column('failed_records', sa.Integer(), nullable=True),
    sa.Column('skipped_records', sa.Integer(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('imported_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bulk_import_jobs')
    # ### end Alembic commands ###
